import * as React from 'react';
import Box from '@mui/material/Box';
import { DataGrid } from '@mui/x-data-grid';

const columns = [
    //   { field: 'id', headerName: 'ID', width: 90 },
    {
        field: 'EMPID',
        headerName: 'EMPID',
        width: 150,
        editable: false,
    },
    {
        field: 'FIRSTNAME',
        headerName: 'FIRST NAME',
        width: 150,
        editable: false,
    },
    {
        field: 'LASTNAME',
        headerName: 'LAST NAME',
        width: 150,
        editable: false,
    },
    {
        field: 'PASSPORT',
        headerName: 'PASSPORT',
        width: 150,
        editable: false,
    },
    {
        field: 'BIRTHDAY',
        headerName: 'BIRTHDAY',
        width: 150,
        editable: false,
    },
    {
        field: 'DEPT',
        headerName: 'DEPARTMENT',
        width: 250,
        editable: false,
    },
    {
        field: 'GENDER',
        headerName: 'GENDER',
        width: 150,
        editable: false,
        // valueGetter: (params) => (params.row.GENDER === '1') ? `Female` : `Male`
    },
    {
        field: 'HIRED',
        headerName: 'HIRED',
        width: 150,
        editable: false,
    },
    {
        field: 'NATIONALITY',
        headerName: 'NATIONALITY',
        width: 150,
        editable: false,
    },
    {
        field: 'POSITION',
        headerName: 'POSITION',
        width: 150,
        editable: false,
    },
    {
        field: 'REGION',
        headerName: 'REGION',
        width: 150,
        editable: false,
    },
    {
        field: 'STATUS',
        headerName: 'STATUS',
        width: 150,
        editable: false,
        // valueGetter: (params) => (params.row.STATUS === '1') ? `Active` : `Resigned`
    }
];


// const datainput2 = [{ id: 1, BIRTHDAY: '28-05-1963', DEPT: 'Pilot', EMPID: 3, FIRSTNAME: 'Jada', GENDER: '0', HIRED: '11-02-2001', LASTNAME: 'Bender', NATIONALITY: 'Pakistan', PASSPORT: 'JUI65YBK7AF', POSITION: 'Pilot', REGION: 'Canada', STATUS: '1' },
// { id: 2, BIRTHDAY: '03-12-1982', DEPT: 'Flight Planning', EMPID: 5, FIRSTNAME: 'Lillian', GENDER: '0', HIRED: '19-05-2002', LASTNAME: 'Reese', NATIONALITY: 'Ukraine', PASSPORT: 'AZE20CSG4MU', POSITION: 'Steward', REGION: 'Canada', STATUS: '1' },
// { id: 3, BIRTHDAY: '24-05-1987', DEPT: 'Aircraft Maintenance', EMPID: 23, FIRSTNAME: 'Armand', GENDER: '0', HIRED: '19-06-2007', LASTNAME: 'Horn', NATIONALITY: 'Netherlands', PASSPORT: 'NFH65BYM0VB', POSITION: 'Airhostess', REGION: 'Ocenia', STATUS: '1' },
// { id: 4, BIRTHDAY: '15-07-1974', DEPT: 'Aircraft Maintenance', EMPID: 29, FIRSTNAME: 'Rowan', GENDER: '1', HIRED: '27-03-2004', LASTNAME: 'Leonard', NATIONALITY: 'Germany', PASSPORT: 'CMK62UAD3VK', POSITION: 'Pilot', REGION: 'Ocenia', STATUS: '1' },
// { id: 5, BIRTHDAY: '23-11-1967', DEPT: 'Flight Planning', EMPID: 33, FIRSTNAME: 'Carter', GENDER: '0', HIRED: '27-02-2005', LASTNAME: 'Velasquez', NATIONALITY: 'Indonesia', PASSPORT: 'EWD45RJW5YK', POSITION: 'Pilot', REGION: 'APAC', STATUS: '1' },
// { id: 6, BIRTHDAY: '26-03-1972', DEPT: 'Flight Attendance', EMPID: 34, FIRSTNAME: 'Selma', GENDER: '0', HIRED: '10-10-2008', LASTNAME: 'Bush', NATIONALITY: 'Italy', PASSPORT: 'BFS82MEY3CX', POSITION: 'Airhostess', REGION: 'USA', STATUS: '1' },
// { id: 7, BIRTHDAY: '16-04-1999', DEPT: 'Flight Attendance', EMPID: 50, FIRSTNAME: 'Calvin', GENDER: '1', HIRED: '18-03-2011', LASTNAME: 'Roach', NATIONALITY: 'Mexico', PASSPORT: 'MRC33GHJ2KW', POSITION: 'Steward', REGION: 'Europe', STATUS: '1' },
// { id: 8, BIRTHDAY: '04-06-1971', DEPT: 'Flight Attendance', EMPID: 66, FIRSTNAME: 'Zachery', GENDER: '0', HIRED: '25-08-2011', LASTNAME: 'Valentine', NATIONALITY: 'Philippines', PASSPORT: 'WKV12UQC6QF', POSITION: 'Steward', REGION: 'Middle East', STATUS: '1' },
// { id: 9, BIRTHDAY: '13-06-1998', DEPT: 'Aircraft Maintenance', EMPID: 80, FIRSTNAME: 'Ryan', GENDER: '0', HIRED: '31-07-2019', LASTNAME: 'Rush', NATIONALITY: 'Italy', PASSPORT: 'EUC74ENE9ZK', POSITION: 'Pilot', REGION: 'Middle East', STATUS: '1' },
// { id: 10, BIRTHDAY: '09-03-1982', DEPT: 'Aircraft Maintenance', EMPID: 93, FIRSTNAME: 'Honorato', GENDER: '1', HIRED: '04-02-2017', LASTNAME: 'Maxwell', NATIONALITY: 'France', PASSPORT: 'UXL43IOW6OV', POSITION: 'Airhostess', REGION: 'Europe', STATUS: '1' },
// { id: 11, BIRTHDAY: '29-06-1996', DEPT: 'Flight Attendance', EMPID: 95, FIRSTNAME: 'Dara', GENDER: '1', HIRED: '18-05-2011', LASTNAME: 'Wilcox', NATIONALITY: 'Singapore', PASSPORT: 'OUP31WOE2IE', POSITION: 'Airhostess', REGION: 'Canada', STATUS: '1' },
// { id: 12, BIRTHDAY: '21-12-1999', DEPT: 'Pilot', EMPID: 97, FIRSTNAME: 'Dante', GENDER: '0', HIRED: '22-02-2016', LASTNAME: 'Hart', NATIONALITY: 'Peru', PASSPORT: 'SUF73DKV4QE', POSITION: 'Pilot', REGION: 'Europe', STATUS: '1' }]



const datainput = [
    {
        id: 1 ,
        EMPID: 1,
        PASSPORT: "OQI75XIE4UX",
        FIRSTNAME: "Christopher",
        LASTNAME: "Kennedy",
        GENDER: 1,
        BIRTHDAY: "05-02-1978",
        NATIONALITY: "South Korea",
        HIRED: "20-02-2005",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Europe"
    },
    {
        id: 2 ,
        EMPID: 2,
        PASSPORT: "CDC87ETW8EQ",
        FIRSTNAME: "Burton",
        LASTNAME: "Gallegos",
        GENDER: 0,
        BIRTHDAY: "22-09-1960",
        NATIONALITY: "Germany",
        HIRED: "29-10-2021",
        DEPT: "Aircraft Maintenance",
        POSITION: "Pilot",
        STATUS: 1,
        REGION: "APAC"
    },
    {
        id: 3 ,
        EMPID: 3,
        PASSPORT: "JUI65YBK7AF",
        FIRSTNAME: "Jada",
        LASTNAME: "Bender",
        GENDER: 0,
        BIRTHDAY: "28-05-1963",
        NATIONALITY: "Pakistan",
        HIRED: "11-02-2001",
        DEPT: "Pilot",
        POSITION: "Pilot",
        STATUS: 1,
        REGION: "Canada"
    },
    {
        id: 4 ,
        EMPID: 4,
        PASSPORT: "CYB72WYU6UR",
        FIRSTNAME: "Winter",
        LASTNAME: "Blair",
        GENDER: 0,
        BIRTHDAY: "14-02-1993",
        NATIONALITY: "Austria",
        HIRED: "24-03-2022",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Ocenia"
    },
    {
        id: 5 ,
        EMPID: 5,
        PASSPORT: "AZE20CSG4MU",
        FIRSTNAME: "Lillian",
        LASTNAME: "Reese",
        GENDER: 0,
        BIRTHDAY: "03-12-1982",
        NATIONALITY: "Ukraine",
        HIRED: "19-05-2002",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 1,
        REGION: "Canada"
    },
    {
        id: 6 ,
        EMPID: 6,
        PASSPORT: "KXU40SKR1YO",
        FIRSTNAME: "Simone",
        LASTNAME: "Mosley",
        GENDER: 0,
        BIRTHDAY: "20-11-1994",
        NATIONALITY: "Norway",
        HIRED: "10-03-2023",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Canada"
    },
    {
        id: 7 ,
        EMPID: 7,
        PASSPORT: "SBJ34IXU7TC",
        FIRSTNAME: "Madeson",
        LASTNAME: "Mcintosh",
        GENDER: 1,
        BIRTHDAY: "03-11-1997",
        NATIONALITY: "Mexico",
        HIRED: "22-08-2007",
        DEPT: "Flight Attendance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Ocenia"
    },
    {
        id: 8 ,
        EMPID: 8,
        PASSPORT: "UCT91SOT6EN",
        FIRSTNAME: "Josephine",
        LASTNAME: "Hansen",
        GENDER: 1,
        BIRTHDAY: "12-10-1982",
        NATIONALITY: "United States",
        HIRED: "24-12-2021",
        DEPT: "Flight Planning",
        POSITION: "Pilot",
        STATUS: 4,
        REGION: "Middle East"
    },
    {
        id: 9 ,
        EMPID: 9,
        PASSPORT: "WOW94MLI6CM",
        FIRSTNAME: "Prescott",
        LASTNAME: "Dudley",
        GENDER: 0,
        BIRTHDAY: "07-04-1990",
        NATIONALITY: "Sweden",
        HIRED: "16-11-2012",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Canada"
    },
    {
        id: 10 ,
        EMPID: 10,
        PASSPORT: "YHF52IXT9VG",
        FIRSTNAME: "Lamar",
        LASTNAME: "Reeves",
        GENDER: 1,
        BIRTHDAY: "13-09-1988",
        NATIONALITY: "Philippines",
        HIRED: "26-09-2003",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 2,
        REGION: "Canada"
    },
    {
        id: 11 ,
        EMPID: 11,
        PASSPORT: "LBI65YUK1BG",
        FIRSTNAME: "Hamilton",
        LASTNAME: "Duffy",
        GENDER: 1,
        BIRTHDAY: "09-11-1987",
        NATIONALITY: "Vietnam",
        HIRED: "31-12-2021",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 12 ,
        EMPID: 12,
        PASSPORT: "KGM77GAL2UW",
        FIRSTNAME: "Levi",
        LASTNAME: "Atkinson",
        GENDER: 0,
        BIRTHDAY: "08-10-1969",
        NATIONALITY: "Sweden",
        HIRED: "13-09-2002",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Europe"
    },
    {
        id: 13 ,
        EMPID: 13,
        PASSPORT: "UOM66JXI0ZD",
        FIRSTNAME: "Levi",
        LASTNAME: "Myers",
        GENDER: 0,
        BIRTHDAY: "29-12-1998",
        NATIONALITY: "Sweden",
        HIRED: "13-09-2004",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 14 ,
        EMPID: 14,
        PASSPORT: "TAP82QBU5PN",
        FIRSTNAME: "Lunea",
        LASTNAME: "Sweet",
        GENDER: 1,
        BIRTHDAY: "27-10-1992",
        NATIONALITY: "Netherlands",
        HIRED: "15-03-2004",
        DEPT: "Pilot",
        POSITION: "Airhostess",
        STATUS: 3,
        REGION: "Middle East"
    },
    {
        id: 15 ,
        EMPID: 15,
        PASSPORT: "MOJ66TSD0LH",
        FIRSTNAME: "Jade",
        LASTNAME: "Simmons",
        GENDER: 1,
        BIRTHDAY: "04-03-1961",
        NATIONALITY: "Costa Rica",
        HIRED: "24-12-2000",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Canada"
    },
    {
        id: 16 ,
        EMPID: 16,
        PASSPORT: "WRS57BWI1RG",
        FIRSTNAME: "Serina",
        LASTNAME: "Tran",
        GENDER: 1,
        BIRTHDAY: "28-11-1980",
        NATIONALITY: "Sweden",
        HIRED: "18-07-2010",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Canada"
    },
    {
        id: 17 ,
        EMPID: 17,
        PASSPORT: "TZU74JZT1GC",
        FIRSTNAME: "Talon",
        LASTNAME: "Santiago",
        GENDER: 1,
        BIRTHDAY: "17-04-1969",
        NATIONALITY: "United States",
        HIRED: "02-09-2015",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Canada"
    },
    {
        id: 18 ,
        EMPID: 18,
        PASSPORT: "DFE84WHT0ED",
        FIRSTNAME: "Joelle",
        LASTNAME: "Boyle",
        GENDER: 0,
        BIRTHDAY: "19-07-1962",
        NATIONALITY: "Germany",
        HIRED: "28-03-2013",
        DEPT: "Flight Planning",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Ocenia"
    },
    {
        id: 19 ,
        EMPID: 19,
        PASSPORT: "SYT22ZIA2ZU",
        FIRSTNAME: "Thaddeus",
        LASTNAME: "Martinez",
        GENDER: 1,
        BIRTHDAY: "02-04-1975",
        NATIONALITY: "Costa Rica",
        HIRED: "11-07-2015",
        DEPT: "Flight Attendance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Middle East"
    },
    {
        id: 20 ,
        EMPID: 20,
        PASSPORT: "JDS74VWV5XG",
        FIRSTNAME: "Lester",
        LASTNAME: "Edwards",
        GENDER: 1,
        BIRTHDAY: "11-10-1973",
        NATIONALITY: "India",
        HIRED: "03-09-2000",
        DEPT: "Flight Planning",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Canada"
    },
    {
        id: 21 ,
        EMPID: 21,
        PASSPORT: "SMN51EPH5FE",
        FIRSTNAME: "Aline",
        LASTNAME: "Riley",
        GENDER: 0,
        BIRTHDAY: "04-06-1989",
        NATIONALITY: "India",
        HIRED: "05-04-2001",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "APAC"
    },
    {
        id: 22 ,
        EMPID: 22,
        PASSPORT: "SOM23XJR5NC",
        FIRSTNAME: "Igor",
        LASTNAME: "Ochoa",
        GENDER: 1,
        BIRTHDAY: "11-10-1972",
        NATIONALITY: "Colombia",
        HIRED: "02-11-2005",
        DEPT: "Flight Planning",
        POSITION: "Airhostess",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 23 ,
        EMPID: 23,
        PASSPORT: "NFH65BYM0VB",
        FIRSTNAME: "Armand",
        LASTNAME: "Horn",
        GENDER: 0,
        BIRTHDAY: "24-05-1987",
        NATIONALITY: "Netherlands",
        HIRED: "19-06-2007",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 1,
        REGION: "Ocenia"
    },
    {
        id: 24 ,
        EMPID: 24,
        PASSPORT: "EQI56KFP6NU",
        FIRSTNAME: "Chaney",
        LASTNAME: "Ramsey",
        GENDER: 1,
        BIRTHDAY: "13-06-1972",
        NATIONALITY: "South Africa",
        HIRED: "19-12-2002",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "USA"
    },
    {
        id: 25 ,
        EMPID: 25,
        PASSPORT: "BJQ37WBQ4UL",
        FIRSTNAME: "Leandra",
        LASTNAME: "Mayer",
        GENDER: 0,
        BIRTHDAY: "07-09-1974",
        NATIONALITY: "Philippines",
        HIRED: "17-09-2019",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 26 ,
        EMPID: 26,
        PASSPORT: "CCE27MGJ8KI",
        FIRSTNAME: "Chloe",
        LASTNAME: "Blanchard",
        GENDER: 1,
        BIRTHDAY: "29-12-1998",
        NATIONALITY: "Russian Federation",
        HIRED: "20-05-2001",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Middle East"
    },
    {
        id: 27 ,
        EMPID: 27,
        PASSPORT: "EDF66USR7HP",
        FIRSTNAME: "Anjolie",
        LASTNAME: "Dudley",
        GENDER: 1,
        BIRTHDAY: "27-12-1975",
        NATIONALITY: "United Kingdom",
        HIRED: "28-07-2004",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "USA"
    },
    {
        id: 28 ,
        EMPID: 28,
        PASSPORT: "VSN53SUD8EA",
        FIRSTNAME: "Lana",
        LASTNAME: "Aguirre",
        GENDER: 1,
        BIRTHDAY: "30-10-1979",
        NATIONALITY: "Pakistan",
        HIRED: "16-09-2020",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 2,
        REGION: "Middle East"
    },
    {
        id: 29 ,
        EMPID: 29,
        PASSPORT: "CMK62UAD3VK",
        FIRSTNAME: "Rowan",
        LASTNAME: "Leonard",
        GENDER: 1,
        BIRTHDAY: "15-07-1974",
        NATIONALITY: "Germany",
        HIRED: "27-03-2004",
        DEPT: "Aircraft Maintenance",
        POSITION: "Pilot",
        STATUS: 1,
        REGION: "Ocenia"
    },
    {
        id: 30 ,
        EMPID: 30,
        PASSPORT: "WJE55UKG3YU",
        FIRSTNAME: "Clarke",
        LASTNAME: "Norman",
        GENDER: 1,
        BIRTHDAY: "15-06-1987",
        NATIONALITY: "Pakistan",
        HIRED: "13-01-2022",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 3,
        REGION: "USA"
    },
    {
        id: 31 ,
        EMPID: 31,
        PASSPORT: "JBK92QBQ9CF",
        FIRSTNAME: "Kyra",
        LASTNAME: "Noel",
        GENDER: 1,
        BIRTHDAY: "25-08-1972",
        NATIONALITY: "China",
        HIRED: "27-11-2005",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 3,
        REGION: "Canada"
    },
    {
        id: 32 ,
        EMPID: 32,
        PASSPORT: "KUO96QIG4VK",
        FIRSTNAME: "Stephen",
        LASTNAME: "Dickson",
        GENDER: 0,
        BIRTHDAY: "02-05-1962",
        NATIONALITY: "Netherlands",
        HIRED: "15-03-2013",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 33 ,
        EMPID: 33,
        PASSPORT: "EWD45RJW5YK",
        FIRSTNAME: "Carter",
        LASTNAME: "Velasquez",
        GENDER: 0,
        BIRTHDAY: "23-11-1967",
        NATIONALITY: "Indonesia",
        HIRED: "27-02-2005",
        DEPT: "Flight Planning",
        POSITION: "Pilot",
        STATUS: 1,
        REGION: "APAC"
    },
    {
        id: 34 ,
        EMPID: 34,
        PASSPORT: "BFS82MEY3CX",
        FIRSTNAME: "Selma",
        LASTNAME: "Bush",
        GENDER: 0,
        BIRTHDAY: "26-03-1972",
        NATIONALITY: "Italy",
        HIRED: "10-10-2008",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 1,
        REGION: "USA"
    },
    {
        id: 35 ,
        EMPID: 35,
        PASSPORT: "XPI62OGX6QX",
        FIRSTNAME: "Roary",
        LASTNAME: "Frank",
        GENDER: 1,
        BIRTHDAY: "30-12-1979",
        NATIONALITY: "South Korea",
        HIRED: "12-11-2008",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 2,
        REGION: "Middle East"
    },
    {
        id: 36 ,
        EMPID: 36,
        PASSPORT: "TLM36YPP3NE",
        FIRSTNAME: "Vera",
        LASTNAME: "Ashley",
        GENDER: 1,
        BIRTHDAY: "02-06-1982",
        NATIONALITY: "Peru",
        HIRED: "12-03-2022",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Canada"
    },
    {
        id: 37 ,
        EMPID: 37,
        PASSPORT: "GWY17TOL2UG",
        FIRSTNAME: "Matthew",
        LASTNAME: "Vasquez",
        GENDER: 1,
        BIRTHDAY: "17-03-1995",
        NATIONALITY: "Ireland",
        HIRED: "01-07-2007",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Ocenia"
    },
    {
        id: 38 ,
        EMPID: 38,
        PASSPORT: "KMG07QVW7MP",
        FIRSTNAME: "Kylynn",
        LASTNAME: "Mullins",
        GENDER: 0,
        BIRTHDAY: "19-04-1979",
        NATIONALITY: "Vietnam",
        HIRED: "07-11-2020",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Middle East"
    },
    {
        id: 39 ,
        EMPID: 39,
        PASSPORT: "DDI37UIV8QD",
        FIRSTNAME: "Trevor",
        LASTNAME: "Wyatt",
        GENDER: 0,
        BIRTHDAY: "14-02-1998",
        NATIONALITY: "Turkey",
        HIRED: "15-03-2010",
        DEPT: "Pilot",
        POSITION: "Airhostess",
        STATUS: 2,
        REGION: "USA"
    },
    {
        id: 40 ,
        EMPID: 40,
        PASSPORT: "JHJ72ODJ7RA",
        FIRSTNAME: "Gregory",
        LASTNAME: "Bryant",
        GENDER: 0,
        BIRTHDAY: "14-09-1968",
        NATIONALITY: "Austria",
        HIRED: "10-01-2017",
        DEPT: "Flight Planning",
        POSITION: "Pilot",
        STATUS: 0,
        REGION: "Middle East"
    },
    {
        id: 41 ,
        EMPID: 41,
        PASSPORT: "ITS61SWZ4PW",
        FIRSTNAME: "Duncan",
        LASTNAME: "Morrison",
        GENDER: 1,
        BIRTHDAY: "24-04-1975",
        NATIONALITY: "Mexico",
        HIRED: "01-03-2012",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 42 ,
        EMPID: 42,
        PASSPORT: "QSP69GYO0YK",
        FIRSTNAME: "Rajah",
        LASTNAME: "Roach",
        GENDER: 0,
        BIRTHDAY: "13-12-1992",
        NATIONALITY: "Costa Rica",
        HIRED: "26-05-2011",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 43 ,
        EMPID: 43,
        PASSPORT: "JWF56EYP2AN",
        FIRSTNAME: "Sophia",
        LASTNAME: "Fuller",
        GENDER: 1,
        BIRTHDAY: "03-01-1986",
        NATIONALITY: "Peru",
        HIRED: "15-02-2012",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 44 ,
        EMPID: 44,
        PASSPORT: "VTF75CUM7PC",
        FIRSTNAME: "Rhea",
        LASTNAME: "Keith",
        GENDER: 0,
        BIRTHDAY: "28-06-2000",
        NATIONALITY: "Costa Rica",
        HIRED: "30-10-2010",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 4,
        REGION: "Canada"
    },
    {
        id: 45 ,
        EMPID: 45,
        PASSPORT: "MIF51GHC3PF",
        FIRSTNAME: "Walker",
        LASTNAME: "Jarvis",
        GENDER: 0,
        BIRTHDAY: "26-06-1988",
        NATIONALITY: "Philippines",
        HIRED: "22-04-2004",
        DEPT: "Aircraft Maintenance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Ocenia"
    },
    {
        id: 46 ,
        EMPID: 46,
        PASSPORT: "ZGJ51FDM2LC",
        FIRSTNAME: "Reese",
        LASTNAME: "Christensen",
        GENDER: 0,
        BIRTHDAY: "15-09-1993",
        NATIONALITY: "Turkey",
        HIRED: "10-08-2011",
        DEPT: "Aircraft Maintenance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Ocenia"
    },
    {
        id: 47 ,
        EMPID: 47,
        PASSPORT: "CQW50GAD3DS",
        FIRSTNAME: "Martin",
        LASTNAME: "Payne",
        GENDER: 1,
        BIRTHDAY: "12-05-1961",
        NATIONALITY: "Austria",
        HIRED: "07-10-2015",
        DEPT: "Pilot",
        POSITION: "Pilot",
        STATUS: 4,
        REGION: "Ocenia"
    },
    {
        id: 48 ,
        EMPID: 48,
        PASSPORT: "MKI89CUF6PR",
        FIRSTNAME: "Fuller",
        LASTNAME: "Alvarez",
        GENDER: 0,
        BIRTHDAY: "06-01-1988",
        NATIONALITY: "Austria",
        HIRED: "30-12-2016",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 49 ,
        EMPID: 49,
        PASSPORT: "PRX53TYM5LT",
        FIRSTNAME: "Macon",
        LASTNAME: "Trevino",
        GENDER: 1,
        BIRTHDAY: "01-10-1997",
        NATIONALITY: "Colombia",
        HIRED: "17-12-2019",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Ocenia"
    },
    {
        id: 50 ,
        EMPID: 50,
        PASSPORT: "MRC33GHJ2KW",
        FIRSTNAME: "Calvin",
        LASTNAME: "Roach",
        GENDER: 1,
        BIRTHDAY: "16-04-1999",
        NATIONALITY: "Mexico",
        HIRED: "18-03-2011",
        DEPT: "Flight Attendance",
        POSITION: "Steward",
        STATUS: 1,
        REGION: "Europe"
    },
    {
        id: 51 ,
        EMPID: 51,
        PASSPORT: "BPO49TXH0XX",
        FIRSTNAME: "Charles",
        LASTNAME: "Kim",
        GENDER: 0,
        BIRTHDAY: "30-12-1968",
        NATIONALITY: "South Africa",
        HIRED: "12-09-2015",
        DEPT: "Flight Planning",
        POSITION: "Pilot",
        STATUS: 2,
        REGION: "Ocenia"
    },
    {
        id: 52 ,
        EMPID: 52,
        PASSPORT: "THN13DDU7PZ",
        FIRSTNAME: "Kieran",
        LASTNAME: "Hancock",
        GENDER: 1,
        BIRTHDAY: "01-07-1976",
        NATIONALITY: "Italy",
        HIRED: "14-04-2023",
        DEPT: "Flight Planning",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "USA"
    },
    {
        id: 53 ,
        EMPID: 53,
        PASSPORT: "EKI78MBL1DM",
        FIRSTNAME: "Irene",
        LASTNAME: "Moon",
        GENDER: 0,
        BIRTHDAY: "02-10-1973",
        NATIONALITY: "United Kingdom",
        HIRED: "21-04-2015",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 2,
        REGION: "USA"
    },
    {
        id: 54 ,
        EMPID: 54,
        PASSPORT: "ZCM30CQE2UN",
        FIRSTNAME: "Noelani",
        LASTNAME: "Watkins",
        GENDER: 0,
        BIRTHDAY: "31-08-1969",
        NATIONALITY: "United Kingdom",
        HIRED: "18-07-2016",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 4,
        REGION: "Europe"
    },
    {
        id: 55 ,
        EMPID: 55,
        PASSPORT: "JJG71FLY1XR",
        FIRSTNAME: "Paula",
        LASTNAME: "Delaney",
        GENDER: 0,
        BIRTHDAY: "18-09-1986",
        NATIONALITY: "Brazil",
        HIRED: "29-01-2003",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Middle East"
    },
    {
        id: 56 ,
        EMPID: 56,
        PASSPORT: "UWS82URG4LM",
        FIRSTNAME: "Keelie",
        LASTNAME: "Crosby",
        GENDER: 0,
        BIRTHDAY: "17-07-1985",
        NATIONALITY: "Vietnam",
        HIRED: "01-04-2002",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "USA"
    },
    {
        id: 57 ,
        EMPID: 57,
        PASSPORT: "GRE66NCT2EF",
        FIRSTNAME: "Aimee",
        LASTNAME: "Stone",
        GENDER: 0,
        BIRTHDAY: "08-09-1990",
        NATIONALITY: "Spain",
        HIRED: "25-07-2007",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Middle East"
    },
    {
        id: 58 ,
        EMPID: 58,
        PASSPORT: "TZT98UWC8BW",
        FIRSTNAME: "Donna",
        LASTNAME: "Clay",
        GENDER: 1,
        BIRTHDAY: "25-12-1977",
        NATIONALITY: "Peru",
        HIRED: "16-05-2003",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 58 ,
        EMPID: 59,
        PASSPORT: "VDF94IVV1UX",
        FIRSTNAME: "Nomlanga",
        LASTNAME: "Stout",
        GENDER: 0,
        BIRTHDAY: "03-04-1975",
        NATIONALITY: "China",
        HIRED: "06-08-2009",
        DEPT: "Flight Planning",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Canada"
    },
    {
        id: 60 ,
        EMPID: 60,
        PASSPORT: "IUE46AKB9OH",
        FIRSTNAME: "Yuri",
        LASTNAME: "Evans",
        GENDER: 1,
        BIRTHDAY: "05-10-1973",
        NATIONALITY: "Vietnam",
        HIRED: "18-04-2022",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Ocenia"
    },
    {
        id: 61 ,
        EMPID: 61,
        PASSPORT: "KGM73NWG1JP",
        FIRSTNAME: "Desirae",
        LASTNAME: "Melton",
        GENDER: 1,
        BIRTHDAY: "07-11-1993",
        NATIONALITY: "Australia",
        HIRED: "12-04-2013",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 62 ,
        EMPID: 62,
        PASSPORT: "LYL50VBA1GL",
        FIRSTNAME: "Armando",
        LASTNAME: "Moody",
        GENDER: 1,
        BIRTHDAY: "24-04-1989",
        NATIONALITY: "Costa Rica",
        HIRED: "15-04-2020",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 3,
        REGION: "USA"
    },
    {
        id: 63 ,
        EMPID: 63,
        PASSPORT: "UVV50TVB3TS",
        FIRSTNAME: "Maggy",
        LASTNAME: "Miles",
        GENDER: 0,
        BIRTHDAY: "16-01-1972",
        NATIONALITY: "Mexico",
        HIRED: "02-08-2015",
        DEPT: "Flight Planning",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Ocenia"
    },
    {
        id: 64 ,
        EMPID: 64,
        PASSPORT: "GSW02GPL6OY",
        FIRSTNAME: "Wyoming",
        LASTNAME: "Joyner",
        GENDER: 0,
        BIRTHDAY: "20-11-1991",
        NATIONALITY: "Turkey",
        HIRED: "17-04-2022",
        DEPT: "Flight Attendance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 65 ,
        EMPID: 65,
        PASSPORT: "UCZ18XLY9OA",
        FIRSTNAME: "Solomon",
        LASTNAME: "Estes",
        GENDER: 0,
        BIRTHDAY: "16-07-1968",
        NATIONALITY: "Philippines",
        HIRED: "08-02-2014",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "USA"
    },
    {
        id: 66 ,
        EMPID: 66,
        PASSPORT: "WKV12UQC6QF",
        FIRSTNAME: "Zachery",
        LASTNAME: "Valentine",
        GENDER: 0,
        BIRTHDAY: "04-06-1971",
        NATIONALITY: "Philippines",
        HIRED: "25-08-2011",
        DEPT: "Flight Attendance",
        POSITION: "Steward",
        STATUS: 1,
        REGION: "Middle East"
    },
    {
        id: 67 ,
        EMPID: 67,
        PASSPORT: "BVY21SKG6CE",
        FIRSTNAME: "Kitra",
        LASTNAME: "Green",
        GENDER: 0,
        BIRTHDAY: "10-07-1967",
        NATIONALITY: "Ireland",
        HIRED: "12-09-2006",
        DEPT: "Flight Planning",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Middle East"
    },
    {
        id: 68 ,
        EMPID: 68,
        PASSPORT: "GDJ74WSM7LG",
        FIRSTNAME: "Autumn",
        LASTNAME: "Page",
        GENDER: 0,
        BIRTHDAY: "01-11-1969",
        NATIONALITY: "Brazil",
        HIRED: "24-04-2001",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 3,
        REGION: "Middle East"
    },
    {
        id: 69 ,
        EMPID: 69,
        PASSPORT: "OOR56TFJ3XV",
        FIRSTNAME: "Nehru",
        LASTNAME: "Vargas",
        GENDER: 1,
        BIRTHDAY: "25-09-1976",
        NATIONALITY: "Germany",
        HIRED: "27-08-2007",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 2,
        REGION: "USA"
    },
    {
        id: 70 ,
        EMPID: 70,
        PASSPORT: "RAX87DEX6CC",
        FIRSTNAME: "Ferris",
        LASTNAME: "Houston",
        GENDER: 0,
        BIRTHDAY: "01-05-1981",
        NATIONALITY: "Singapore",
        HIRED: "23-02-2016",
        DEPT: "Pilot",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Canada"
    },
    {
        id: 71 ,
        EMPID: 71,
        PASSPORT: "FSQ47TYA9DJ",
        FIRSTNAME: "Pascale",
        LASTNAME: "Silva",
        GENDER: 0,
        BIRTHDAY: "13-10-1968",
        NATIONALITY: "Netherlands",
        HIRED: "27-09-2007",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Canada"
    },
    {
        id: 72 ,
        EMPID: 72,
        PASSPORT: "AUY27DLM5FK",
        FIRSTNAME: "Leilani",
        LASTNAME: "Moran",
        GENDER: 0,
        BIRTHDAY: "25-08-1996",
        NATIONALITY: "Belgium",
        HIRED: "08-04-2005",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 2,
        REGION: "Ocenia"
    },
    {
        id: 73 ,
        EMPID: 73,
        PASSPORT: "XIJ68PKR7QT",
        FIRSTNAME: "Darius",
        LASTNAME: "Serrano",
        GENDER: 0,
        BIRTHDAY: "29-04-1990",
        NATIONALITY: "United States",
        HIRED: "03-11-2005",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Middle East"
    },
    {
        id: 74 ,
        EMPID: 74,
        PASSPORT: "HJL93JJY5GH",
        FIRSTNAME: "September",
        LASTNAME: "Morin",
        GENDER: 1,
        BIRTHDAY: "15-09-1997",
        NATIONALITY: "Mexico",
        HIRED: "26-08-2014",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 75 ,
        EMPID: 75,
        PASSPORT: "KVI04NMS2QH",
        FIRSTNAME: "Shay",
        LASTNAME: "Mcdonald",
        GENDER: 1,
        BIRTHDAY: "29-12-1999",
        NATIONALITY: "South Africa",
        HIRED: "07-03-2007",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 4,
        REGION: "Ocenia"
    },
    {
        id: 76 ,
        EMPID: 76,
        PASSPORT: "YWT45VVP7KK",
        FIRSTNAME: "Nathan",
        LASTNAME: "Floyd",
        GENDER: 0,
        BIRTHDAY: "04-01-1988",
        NATIONALITY: "Australia",
        HIRED: "09-10-2008",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 3,
        REGION: "USA"
    },
    {
        id: 77 ,
        EMPID: 77,
        PASSPORT: "EOP89YXA3YW",
        FIRSTNAME: "Wayne",
        LASTNAME: "Bowman",
        GENDER: 0,
        BIRTHDAY: "02-03-1991",
        NATIONALITY: "Vietnam",
        HIRED: "28-03-2007",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "APAC"
    },
    {
        id: 78 ,
        EMPID: 78,
        PASSPORT: "YHV05IUP6ER",
        FIRSTNAME: "Willa",
        LASTNAME: "Ferguson",
        GENDER: 0,
        BIRTHDAY: "10-12-1969",
        NATIONALITY: "Italy",
        HIRED: "08-07-2017",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 3,
        REGION: "Ocenia"
    },
    {
        id: 79 ,
        EMPID: 79,
        PASSPORT: "RCQ71JXX4NH",
        FIRSTNAME: "Teagan",
        LASTNAME: "Daniel",
        GENDER: 1,
        BIRTHDAY: "02-09-1983",
        NATIONALITY: "United States",
        HIRED: "22-05-2005",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "APAC"
    },
    {
        id: 80 ,
        EMPID: 80,
        PASSPORT: "EUC74ENE9ZK",
        FIRSTNAME: "Ryan",
        LASTNAME: "Rush",
        GENDER: 0,
        BIRTHDAY: "13-06-1998",
        NATIONALITY: "Italy",
        HIRED: "31-07-2019",
        DEPT: "Aircraft Maintenance",
        POSITION: "Pilot",
        STATUS: 1,
        REGION: "Middle East"
    },
    {
        id: 81 ,
        EMPID: 81,
        PASSPORT: "DCD61JXD7UO",
        FIRSTNAME: "Brady",
        LASTNAME: "Hernandez",
        GENDER: 1,
        BIRTHDAY: "26-11-1961",
        NATIONALITY: "Russian Federation",
        HIRED: "01-09-2022",
        DEPT: "Pilot",
        POSITION: "Airhostess",
        STATUS: 2,
        REGION: "Europe"
    },
    {
        id: 82 ,
        EMPID: 82,
        PASSPORT: "ISX87UNW0AD",
        FIRSTNAME: "Herrod",
        LASTNAME: "Oliver",
        GENDER: 0,
        BIRTHDAY: "07-01-1965",
        NATIONALITY: "Peru",
        HIRED: "16-01-2023",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 83 ,
        EMPID: 83,
        PASSPORT: "LJK19GHE1TM",
        FIRSTNAME: "Dalton",
        LASTNAME: "Roberson",
        GENDER: 0,
        BIRTHDAY: "02-05-1994",
        NATIONALITY: "New Zealand",
        HIRED: "21-06-2012",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 84 ,
        EMPID: 84,
        PASSPORT: "KMS88HTI5IR",
        FIRSTNAME: "Chanda",
        LASTNAME: "Wynn",
        GENDER: 1,
        BIRTHDAY: "10-07-1993",
        NATIONALITY: "Indonesia",
        HIRED: "20-11-2014",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "USA"
    },
    {
        id: 85 ,
        EMPID: 85,
        PASSPORT: "MUE55VMY6MX",
        FIRSTNAME: "Solomon",
        LASTNAME: "Booker",
        GENDER: 0,
        BIRTHDAY: "28-03-1961",
        NATIONALITY: "Nigeria",
        HIRED: "18-09-2007",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 3,
        REGION: "APAC"
    },
    {
        id: 86 ,
        EMPID: 86,
        PASSPORT: "WND47SBT6OF",
        FIRSTNAME: "Yardley",
        LASTNAME: "Buckley",
        GENDER: 1,
        BIRTHDAY: "24-06-1989",
        NATIONALITY: "Singapore",
        HIRED: "04-06-2002",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "USA"
    },
    {
        id: 87 ,
        EMPID: 87,
        PASSPORT: "RVO63HMC4NL",
        FIRSTNAME: "Ferris",
        LASTNAME: "Gilbert",
        GENDER: 0,
        BIRTHDAY: "24-07-1969",
        NATIONALITY: "Peru",
        HIRED: "25-12-2002",
        DEPT: "Flight Planning",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Europe"
    },
    {
        id: 88 ,
        EMPID: 88,
        PASSPORT: "TRJ51LBJ6II",
        FIRSTNAME: "Shaeleigh",
        LASTNAME: "Roth",
        GENDER: 1,
        BIRTHDAY: "04-02-1986",
        NATIONALITY: "India",
        HIRED: "15-03-2004",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Europe"
    },
    {
        id: 89 ,
        EMPID: 89,
        PASSPORT: "PHE40UOS0GY",
        FIRSTNAME: "Amanda",
        LASTNAME: "Schwartz",
        GENDER: 1,
        BIRTHDAY: "03-04-1983",
        NATIONALITY: "Vietnam",
        HIRED: "06-08-2019",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "APAC"
    },
    {
        id: 90 ,
        EMPID: 90,
        PASSPORT: "MCJ12FYX5KN",
        FIRSTNAME: "Maxine",
        LASTNAME: "Branch",
        GENDER: 1,
        BIRTHDAY: "29-05-1979",
        NATIONALITY: "Norway",
        HIRED: "17-10-2018",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "Europe"
    },
    {
        id: 91 ,
        EMPID: 91,
        PASSPORT: "WEA16MFX7OE",
        FIRSTNAME: "Drew",
        LASTNAME: "Gordon",
        GENDER: 0,
        BIRTHDAY: "31-10-1981",
        NATIONALITY: "Sweden",
        HIRED: "19-04-2015",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 2,
        REGION: "Ocenia"
    },
    {
        id: 92 ,
        EMPID: 92,
        PASSPORT: "HET44XPQ0RR",
        FIRSTNAME: "Lucy",
        LASTNAME: "Finch",
        GENDER: 1,
        BIRTHDAY: "21-02-1975",
        NATIONALITY: "Indonesia",
        HIRED: "19-05-2002",
        DEPT: "Pilot",
        POSITION: "Steward",
        STATUS: 4,
        REGION: "Middle East"
    },
    {
        id: 93 ,
        EMPID: 93,
        PASSPORT: "UXL43IOW6OV",
        FIRSTNAME: "Honorato",
        LASTNAME: "Maxwell",
        GENDER: 1,
        BIRTHDAY: "09-03-1982",
        NATIONALITY: "France",
        HIRED: "04-02-2017",
        DEPT: "Aircraft Maintenance",
        POSITION: "Airhostess",
        STATUS: 1,
        REGION: "Europe"
    },
    {
        id: 94 ,
        EMPID: 94,
        PASSPORT: "BVQ96KDP3EL",
        FIRSTNAME: "Darryl",
        LASTNAME: "Nichols",
        GENDER: 1,
        BIRTHDAY: "29-05-1988",
        NATIONALITY: "Ukraine",
        HIRED: "19-02-2001",
        DEPT: "Aircraft Maintenance",
        POSITION: "Steward",
        STATUS: 0,
        REGION: "USA"
    },
    {
        id: 95 ,
        EMPID: 95,
        PASSPORT: "OUP31WOE2IE",
        FIRSTNAME: "Dara",
        LASTNAME: "Wilcox",
        GENDER: 1,
        BIRTHDAY: "29-06-1996",
        NATIONALITY: "Singapore",
        HIRED: "18-05-2011",
        DEPT: "Flight Attendance",
        POSITION: "Airhostess",
        STATUS: 1,
        REGION: "Canada"
    },
    {
        id: 96 ,
        EMPID: 96,
        PASSPORT: "LJB26BQM6PS",
        FIRSTNAME: "Laith",
        LASTNAME: "Whitfield",
        GENDER: 0,
        BIRTHDAY: "14-01-1987",
        NATIONALITY: "Russian Federation",
        HIRED: "09-02-2001",
        DEPT: "Pilot",
        POSITION: "Airhostess",
        STATUS: 0,
        REGION: "APAC"
    },
    {
        id: 97 ,
        EMPID: 97,
        PASSPORT: "SUF73DKV4QE",
        FIRSTNAME: "Dante",
        LASTNAME: "Hart",
        GENDER: 0,
        BIRTHDAY: "21-12-1999",
        NATIONALITY: "Peru",
        HIRED: "22-02-2016",
        DEPT: "Pilot",
        POSITION: "Pilot",
        STATUS: 1,
        REGION: "Europe"
    },
    {
        id: 98 ,
        EMPID: 98,
        PASSPORT: "DOB31QXV4GZ",
        FIRSTNAME: "Moana",
        LASTNAME: "Walsh",
        GENDER: 1,
        BIRTHDAY: "03-05-1995",
        NATIONALITY: "Brazil",
        HIRED: "21-04-2002",
        DEPT: "Pilot",
        POSITION: "Airhostess",
        STATUS: 3,
        REGION: "Ocenia"
    },
    {
        id: 99 ,
        EMPID: 99,
        PASSPORT: "OUB92IKA7AU",
        FIRSTNAME: "Jonah",
        LASTNAME: "Solomon",
        GENDER: 1,
        BIRTHDAY: "25-05-1985",
        NATIONALITY: "Pakistan",
        HIRED: "30-04-2023",
        DEPT: "Flight Attendance",
        POSITION: "Pilot",
        STATUS: 3,
        REGION: "Europe"
    },
    {
        id: 100 ,
        EMPID: 100,
        PASSPORT: "WIN16ELU8GN",
        FIRSTNAME: "Orlando",
        LASTNAME: "Mayer",
        GENDER: 0,
        BIRTHDAY: "11-01-1961",
        NATIONALITY: "Austria",
        HIRED: "07-04-2003",
        DEPT: "Pilot",
        POSITION: "Pilot",
        STATUS: 0,
        REGION: "APAC"
    }
]

export default function Table2() {
    return (
        <Box sx={{ height: 800, width: '100%', backgroundColor: "#FFFF", borderRadius: 2 }}>
            <DataGrid
                rows={datainput}
                columns={columns}
                pageSize={25}
                rowsPerPageOptions={[10]}
                // checkboxSelection
                disableSelectionOnClick
            // experimentalFeatures={{ newEditingApi: true }}
            />
        </Box>
    );
}